### ISSUE TITLE
No way to turn off FpsMeter

### ISSUE THREAD

**Issue by trc492** [OpenFTC/Extracted-RC#3]
For last season, you can turn off FpsMeter by calling OpenCvCamera.showFpsMeterOnViewport(false). With the new VisionPortal, you no longer have access to OpenCvCamera. Therefore, it is not easy to turn off the FpsMeter that blocks a substantial area of the lower left corner of the viewport.

**Comment by Windwoes** [comment]
You should file this on https://github.com/FIRST-Tech-Challenge/FtcRobotController

**Comment by Windwoes** [comment]
Closing in favor of issue on official repo
