### ISSUE TITLE
2024-2025

### ISSUE THREAD

**Issue by mucookul** [OpenFTC/Extracted-RC#5]
This repo isn't updated to 10.0 yet. Released a couple days ago

**Comment by Windwoes** [comment]
Yes, it will be updated soon. 10.0 only just went live Saturday afternoon.

**Comment by mucookul** [comment]
Ok

**Comment by Iris-TheRainbow** [comment]
@Windwoes I did fork and add 10.0 manually, if you want me to pr. Im not sure if its perfect, though.

**Comment by Windwoes** [comment]
> @Windwoes I did fork and add 10.0 manually, if you want me to pr. Im not sure if its perfect, though.

Thanks, I'll take care of it though. At minimum, you don't have the updated C++ source because that is not released as part of the official SDK.

**Comment by Windwoes** [comment]
Updated
